<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootableInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\Runtime\BootableInterface' shared autowired service.
     *
     * @return \K911\Swoole\Server\Runtime\CallableBootManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/BootableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/CallableBootManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/CallableBootManagerFactory.php';

        return $container->privates['K911\\Swoole\\Server\\Runtime\\BootableInterface'] = (new \K911\Swoole\Server\Runtime\CallableBootManagerFactory())->make(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['K911\\Swoole\\Bridge\\Symfony\\HttpFoundation\\SetRequestRuntimeConfiguration'] ?? ($container->privates['K911\\Swoole\\Bridge\\Symfony\\HttpFoundation\\SetRequestRuntimeConfiguration'] = new \K911\Swoole\Bridge\Symfony\HttpFoundation\SetRequestRuntimeConfiguration()));
            yield 1 => ($container->privates['K911\\Swoole\\Bridge\\Symfony\\HttpKernel\\HttpKernelRequestHandler'] ?? $container->load('getHttpKernelRequestHandlerService'));
            yield 2 => ($container->privates['K911\\Swoole\\Server\\RequestHandler\\LimitedRequestHandler'] ?? $container->load('getLimitedRequestHandlerService'));
            yield 3 => ($container->privates['K911\\Swoole\\Server\\RequestHandler\\AdvancedStaticFilesServer'] ?? $container->load('getAdvancedStaticFilesServerService'));
        }, 4));
    }
}
