<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpServerConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\HttpServerConfiguration' shared autowired service.
     *
     * @return \K911\Swoole\Server\HttpServerConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/HttpServerConfiguration.php';

        return $container->privates['K911\\Swoole\\Server\\HttpServerConfiguration'] = new \K911\Swoole\Server\HttpServerConfiguration(($container->privates['K911\\Swoole\\Server\\Config\\Sockets'] ?? $container->load('getSocketsService')), 'process', ['log_file' => (\dirname(__DIR__, 3).'/log/swoole_dev.log'), 'log_level' => 'debug', 'pid_file' => NULL, 'buffer_output_size' => 2097152, 'package_max_length' => 8388608, 'worker_count' => 1, 'reactor_count' => 1, 'task_worker_count' => NULL, 'worker_max_request' => 0, 'worker_max_request_grace' => NULL, 'serve_static' => 'advanced', 'public_dir' => (\dirname(__DIR__, 4).'/public')]);
    }
}
