<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLimitedRequestHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\RequestHandler\LimitedRequestHandler' shared autowired service.
     *
     * @return \K911\Swoole\Server\RequestHandler\LimitedRequestHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/RequestHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/BootableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/LimitedRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Component/AtomicCounter.php';

        return $container->privates['K911\\Swoole\\Server\\RequestHandler\\LimitedRequestHandler'] = new \K911\Swoole\Server\RequestHandler\LimitedRequestHandler(($container->privates['K911\\Swoole\\Server\\RequestHandler\\AdvancedStaticFilesServer'] ?? $container->load('getAdvancedStaticFilesServerService')), ($container->privates['K911\\Swoole\\Server\\HttpServer'] ?? $container->load('getHttpServerService')), \K911\Swoole\Component\AtomicCounter::fromZero());
    }
}
