<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServerRunCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Bridge\Symfony\Bundle\Command\ServerRunCommand' shared autowired service.
     *
     * @return \K911\Swoole\Bridge\Symfony\Bundle\Command\ServerRunCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/Bundle/Command/ServerRunCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/ConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/CallableChainConfigurator.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/CallableChainConfiguratorFactory.php';

        $container->privates['K911\\Swoole\\Bridge\\Symfony\\Bundle\\Command\\ServerRunCommand'] = $instance = new \K911\Swoole\Bridge\Symfony\Bundle\Command\ServerRunCommand(($container->privates['K911\\Swoole\\Server\\HttpServer'] ?? $container->load('getHttpServerService')), ($container->privates['K911\\Swoole\\Server\\HttpServerConfiguration'] ?? $container->load('getHttpServerConfigurationService')), ($container->privates['K911\\Swoole\\Server\\Configurator\\CallableChainConfiguratorFactory'] ?? ($container->privates['K911\\Swoole\\Server\\Configurator\\CallableChainConfiguratorFactory'] = new \K911\Swoole\Server\Configurator\CallableChainConfiguratorFactory()))->make(($container->privates['swoole_bundle.server.http_server.configurator_collection'] ?? $container->load('getSwooleBundle_Server_HttpServer_ConfiguratorCollectionService')), ($container->privates['swoole_bundle.server.http_server.configurator.with_request_handler'] ?? $container->load('getSwooleBundle_Server_HttpServer_Configurator_WithRequestHandlerService')), ($container->privates['swoole_bundle.server.http_server.configurator.with_sigint_handler'] ?? $container->load('getSwooleBundle_Server_HttpServer_Configurator_WithSigintHandlerService'))), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->privates['K911\\Swoole\\Server\\Runtime\\BootableInterface'] ?? $container->load('getBootableInterfaceService')));

        $instance->setName('swoole:server:run');

        return $instance;
    }
}
