<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServerStatusCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Bridge\Symfony\Bundle\Command\ServerStatusCommand' shared autowired service.
     *
     * @return \K911\Swoole\Bridge\Symfony\Bundle\Command\ServerStatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/Bundle/Command/ServerStatusCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Api/ApiServerClientFactory.php';

        $a = ($container->privates['K911\\Swoole\\Server\\Config\\Sockets'] ?? $container->load('getSocketsService'));

        $container->privates['K911\\Swoole\\Bridge\\Symfony\\Bundle\\Command\\ServerStatusCommand'] = $instance = new \K911\Swoole\Bridge\Symfony\Bundle\Command\ServerStatusCommand($a, new \K911\Swoole\Server\Api\ApiServerClientFactory($a), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));

        $instance->setName('swoole:server:status');

        return $instance;
    }
}
