<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWithTaskFinishedHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\Configurator\WithTaskFinishedHandler' shared autowired service.
     *
     * @return \K911\Swoole\Server\Configurator\WithTaskFinishedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/ConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/WithTaskFinishedHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/TaskHandler/TaskFinishedHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/TaskHandler/NoOpTaskFinishedHandler.php';

        return $container->privates['K911\\Swoole\\Server\\Configurator\\WithTaskFinishedHandler'] = new \K911\Swoole\Server\Configurator\WithTaskFinishedHandler(new \K911\Swoole\Server\TaskHandler\NoOpTaskFinishedHandler(), ($container->privates['K911\\Swoole\\Server\\HttpServerConfiguration'] ?? $container->load('getHttpServerConfigurationService')));
    }
}
