<?php

namespace ContainerAmmguW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWithServerManagerStartHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\Configurator\WithServerManagerStartHandler' shared autowired service.
     *
     * @return \K911\Swoole\Server\Configurator\WithServerManagerStartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/ConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/WithServerManagerStartHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/LifecycleHandler/ServerManagerStartHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/LifecycleHandler/NoOpServerManagerStartHandler.php';

        return $container->privates['K911\\Swoole\\Server\\Configurator\\WithServerManagerStartHandler'] = new \K911\Swoole\Server\Configurator\WithServerManagerStartHandler(new \K911\Swoole\Server\LifecycleHandler\NoOpServerManagerStartHandler());
    }
}
