<?php

namespace ContainerOWmtgId;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvancedStaticFilesServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\RequestHandler\AdvancedStaticFilesServer' shared service.
     *
     * @return \K911\Swoole\Server\RequestHandler\AdvancedStaticFilesServer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/RequestHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/BootableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/AdvancedStaticFilesServer.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpKernel/DebugHttpKernelRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/ExceptionRequestHandler.php';

        return $container->privates['K911\\Swoole\\Server\\RequestHandler\\AdvancedStaticFilesServer'] = new \K911\Swoole\Server\RequestHandler\AdvancedStaticFilesServer(new \K911\Swoole\Bridge\Symfony\HttpKernel\DebugHttpKernelRequestHandler(new \K911\Swoole\Server\RequestHandler\ExceptionRequestHandler(($container->privates['K911\\Swoole\\Bridge\\Symfony\\HttpKernel\\HttpKernelRequestHandler'] ?? $container->load('getHttpKernelRequestHandlerService')), ($container->privates['K911\\Swoole\\Server\\RequestHandler\\ExceptionHandler\\JsonExceptionHandler'] ?? $container->load('getJsonExceptionHandlerService'))), ($container->services['kernel'] ?? $container->get('kernel', 1)), $container), ($container->privates['K911\\Swoole\\Server\\HttpServerConfiguration'] ?? $container->load('getHttpServerConfigurationService')), []);
    }
}
