<?php

namespace ContainerOWmtgId;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpKernelRequestHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler' shared autowired service.
     *
     * @return \K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/RequestHandler/RequestHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Runtime/BootableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/RequestFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/ResponseProcessorInjectorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/ResponseProcessorInjector.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/ResponseProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/ResponseHeadersAndStatusProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/StreamedResponseProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/NoOpStreamedResponseProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Bridge/Symfony/HttpFoundation/ResponseProcessor.php';

        return $container->privates['K911\\Swoole\\Bridge\\Symfony\\HttpKernel\\HttpKernelRequestHandler'] = new \K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler(($container->services['kernel'] ?? $container->get('kernel', 1)), new \K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactory(), new \K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector(new \K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor(new \K911\Swoole\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor())), new \K911\Swoole\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor(new \K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor(new \K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessor())));
    }
}
