<?php

namespace ContainerOWmtgId;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWithServerStartHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\Configurator\WithServerStartHandler' shared autowired service.
     *
     * @return \K911\Swoole\Server\Configurator\WithServerStartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/ConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/WithServerStartHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/LifecycleHandler/ServerStartHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/LifecycleHandler/NoOpServerStartHandler.php';

        return $container->privates['K911\\Swoole\\Server\\Configurator\\WithServerStartHandler'] = new \K911\Swoole\Server\Configurator\WithServerStartHandler(($container->privates['K911\\Swoole\\Server\\LifecycleHandler\\ServerStartHandlerInterface'] ?? ($container->privates['K911\\Swoole\\Server\\LifecycleHandler\\ServerStartHandlerInterface'] = new \K911\Swoole\Server\LifecycleHandler\NoOpServerStartHandler())), ($container->privates['K911\\Swoole\\Server\\HttpServerConfiguration'] ?? $container->load('getHttpServerConfigurationService')));
    }
}
