<?php

namespace ContainerOWmtgId;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWithWorkerStartHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'K911\Swoole\Server\Configurator\WithWorkerStartHandler' shared autowired service.
     *
     * @return \K911\Swoole\Server\Configurator\WithWorkerStartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/ConfiguratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/Configurator/WithWorkerStartHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/WorkerHandler/WorkerStartHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/k911/swoole-bundle/src/Server/WorkerHandler/NoOpWorkerStartHandler.php';

        return $container->privates['K911\\Swoole\\Server\\Configurator\\WithWorkerStartHandler'] = new \K911\Swoole\Server\Configurator\WithWorkerStartHandler(new \K911\Swoole\Server\WorkerHandler\NoOpWorkerStartHandler());
    }
}
