<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWmtgId\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWmtgId/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWmtgId.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWmtgId\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWmtgId\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWmtgId',
    'container.build_id' => '8c80ed6b',
    'container.build_time' => 1639254028,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWmtgId');
