<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'flow_save' => [[], ['_controller' => 'App\\Controller\\FlowController::save'], [], [['text', '/flow']], [], []],
    'flow_load' => [[], ['_controller' => 'App\\Controller\\FlowController::load'], [], [['text', '/flow']], [], []],
];
